name: ci-pipeline

####
# Start Trigger Definition
###
on:
  push:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    # Only run if Build succeeded
    # Use a condition to ensure the job runs only if the prior workflow succeeded
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy application
        run: echo "Deployment started after successful CI run"
        # Additional steps to download artifacts from the previous workflow go here
      - name: Run deployment
        run: echo "The tests passed. Starting deployment... ${{toJSON(github.event)}}"
      # ... other deployment steps

      - name: Upload Build Data
        uses: actions/upload-artifact@v4
        with:
          name: build-data
          path: . # This uploads EVERYTHING in the current directory. 
                  # Change this to a specific folder (like 'dist/') if you only need certain files.