name: ci-pipeline

####
# Start Trigger Definition
###
on:
  push:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    # Only run if Build succeeded
    # Use a condition to ensure the job runs only if the prior workflow succeeded
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          echo "Building... (simulating build output)"
          echo "This is some data" > build_output.txt

      - name: Upload Build Data
        uses: actions/upload-artifact@v4
        with:
          name: build-data
          path: . # This uploads EVERYTHING in the current directory. 
                  # Change this to a specific folder (like 'dist/') if you only need certain files.
          if-no-files-found: error