name: Terraform GitHub Actions and AWS (JWT from GitHub's OpenID Connect)

####
# Start Trigger Definition
###
on:
  # push:
  #   branches: ["main"]
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

####
# Start Jobs Definition
###
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"

  terraform:
    name: Terraform appply with AWS
    runs-on: ubuntu-latest
    # Pass backend configuration and cloud credentials via environment variables or secrets
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    permissions:
      id-token: write # This permission setting enables the workflow to request and use a JSON Web Token (JWT) from GitHub's OpenID Connect (OIDC) provider. 
      contents: read # This permission grants the GITHUB_TOKEN read-only access to the repository's contents (for actions/checkout@v2). 
    
    defaults:
      run:
        working-directory: tr_src

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Establish an AWS Account
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }} #   e
          aws-region: ${{ secrets.AWS_REGION }} #   us-east-1
          # role-session-name: GitHub-OIDC-TERRAFORM
      
      # Establish a Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false
      
      - name: Print assumed role
        run: aws sts get-caller-identity
      
      - name: Print EC2 vpc-ee9f0e85 InternetGateways
        run: |
          aws ec2 describe-internet-gateways \
          --filters "Name=attachment.vpc-id,Values=vpc-ee9f0e85" \
          --query "InternetGateways[*].InternetGatewayId" \
          --output text

      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        env:
          TF_VAR_vpc_cidr: "10.0.0.0/16"
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - run: |
          echo "steps.plan.outcome :${{ toJson(steps.plan) }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
      - run:  |
          pwd
          ls  -ltra
      - run: echo "Terraform status steps :${{ toJson(steps) }}"

      - name: List files in the repository (tree)
        run: tree .