name: terraform-setup-aws # Setup AWS resources using Terraform and GitHub Actions (JWT from GitHub's OpenID Connect)

####
# Getting start first Trigger Definition
###
on:
  workflow_run:
    workflows: ["ci-pipeline"] # Name of the first workflow
    types: [completed]


####
# Getting start trigger the schedule for this job definition. 
###
jobs:
 
  terraform:
    # Only run if the CI pipeline actually succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Set up AWS through Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This permission setting enables the workflow to request and use a JSON Web Token (JWT) from GitHub's OpenID Connect (OIDC) provider. 
      contents: read # This permission grants the GITHUB_TOKEN read-only access to the repository's contents (for actions/checkout@v2). 
    
    defaults:
      run:
        working-directory: tr_src

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-data
          # This ID ensures you get/Download data from the specific CI run that triggered
          run-id: ${{ github.event.workflow_run.id }} 
          # This tells GitHub to look at the specific CI run that just finished
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          # Path ensures the data lands inside your terraform directory
          path: tr_src/

      - name: Check files artifact downloaded
        run: ls -R # This will show you exactly what was downloaded

      - run: echo "Deploying..."

      # - name: Checkout
      #   uses: actions/checkout@v2

      # Establish an AWS Account
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }} 
          aws-region: ${{ secrets.AWS_REGION }} #   us-east-1
          # role-session-name: GitHub-OIDC-TERRAFORM
      
      # Establish a Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false
      #
      - name: Terraform Format
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        id: init
        run: terraform init
      #
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      #
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - run: |
          echo "steps.plan.outcome :${{ toJson(steps.plan) }}"
      #
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
      - run:  |
          pwd
          ls  -ltra
      - run: echo "Terraform status steps :${{ toJson(steps) }}"
      #
      - name: List files in the repository (tree)
        run: tree .